# Problem rubnih vrijednosti



## Klasifikacija

Neka je 

$$ 
a\cdot u_{xx}+b\cdot u_{xt}+c\cdot u_{tt}+d\cdot u_x+e\cdot u_t + f\cdot u + g = 0
$$

i neka je

$$
D=b^2-4ac.
$$

Vrijedi sljedeća klasifikacija:

|D | D=0  | D<0 | D>0 |  
|:---:|:---:|:--:|:---:|
|Vrsta| parabolička | eliptička | hiperbolička |
|Problem| difuzija  | ravnoteža | valovi   |
|Domena / Metoda | omeđena / SLP | omeđena / SLP |   |
|Domena / Metoda | neomeđena / integr. trans. | neomeđena / integr. trans. | |

Za neomeđeni interval $(0,\infty)$ koristi se Laplaceova transformacija, a za interval $(-\infty,\infty)$ koristi se Fourierova transformacija.

## Jednadžba difuzije

Zadan je problem 

\begin{align*}
& u_t-u_{xx}=0  \\
& u(x,0)=|x|, \quad -2<x<2 \\
& u_x(-2,t)=0, \quad u_x(2,t)=0, \quad t>0 
\end{align*}

Pretpostavimo separaciju varijabli (rješenje je jedinstveno pa je svaka pretpostavka korektna ako daje rješenje):

$$
u(x,t)=X(x)T(t).
$$ 

Uvrštavanje u jednadžbu daje

$$
XT'=X''T
$$

odnosno (stavljamo $-\lambda$ po dogovoru)

$$
\frac{T'}{T}=\frac{X''}{X}=-\lambda,
$$

za neki $\lambda \in\mathbb{R}$.

Dobili smo SLP i populacijsku jednadžbu:

1. SLP: $ X''+\lambda X=0$ uz uvjete $X'(-2)=0$ i $X'(2)=0$
2. Populacijska jednadžba: $T'+\lambda T=0$

Analizirajmo tri slučaja.

*Slučaj 1*,  $\lambda=0$:

Rješenje jednadžbe $X''=0$ je $X=ax+b$ pa je $X'=a$. Rubni uvjet u lijevoj strani daje 
$X'(-2)=a=0$ pa je $X=b=konst.$ svojstvena funkcija, a $\lambda_0=0$ svojstvena vrijednost.

*Slučaj 2*, $\lambda<0$:

Rješenje jednadžbe $X''=-\lambda X$ je $X=a e^{\sqrt{-\lambda}x}+ b e^{-\sqrt{-\lambda}x}$.
Vrijedi 

$$X'=a\sqrt{-\lambda} e^{\sqrt{-\lambda}x}- b\sqrt{-\lambda} e^{-\sqrt{-\lambda}x}.$$

Uvrštavanje rubnih uvjeta daje

\begin{align*}
X'(-2)& =\sqrt{-\lambda} \big(a e^{-2\sqrt{-\lambda}}-be^{2\sqrt{-\lambda}}\big)=0\\
X'(2) & = \sqrt{-\lambda} \big(a e^{2\sqrt{-\lambda}}-be^{-2\sqrt{-\lambda}}\big)=0.
\end{align*}

Iz prve jednadžbe slijedi $a=be^{4\sqrt{-\lambda}}$ pa uvrštavanje u drugu jednadžbu daje
$b\big(e^{6\sqrt{-\lambda}}-e^{-2\sqrt{-\lambda}}\big)=0$. Izraz u zagradi je nula samo za $\lambda=0$ pa je $b=0$. Iz prve jednadžbe onda slijedi $a=0$. Dakle, $X=0$ ne može biti svojstvena funkcija pa $\lambda<0$ nije svojstvena vrijednost.

*Slučaj 3*, $\lambda>0$:

Rješenje jednadžbe $X''=-\lambda X$ je $X=a \sin \sqrt{\lambda}x+ b \cos\sqrt{\lambda}x$.
Početni uvjet $u(x,0)=|x|$ je parna funkcija pa možemo uzati koeficijent uz $\sin(\sqrt{\lambda}x)$ jednak nuli. Dakle, $X=b \cos\sqrt{\lambda}x$ pa je $X'=-b\sqrt{\lambda}\sin\sqrt{\lambda}x$. Rubni uvjeti daju

\begin{align*}
X'(-2)& =-b\sqrt{\lambda}\sin(-2\sqrt{\lambda})=b\sqrt{\lambda}\sin(2\sqrt{\lambda})=0 \\
X'(2) & = b\sqrt{\lambda}\sin(2\sqrt{\lambda})=0.
\end{align*}

Kako je $b\neq 0$ i $\sqrt{\lambda}\neq 0$, vrijedi $2\sqrt{\lambda}=n\pi$, $n\in\mathbb{N}$. 

Dakle, za $\lambda \geq 0$ SLP ima beskonačno svojstvenih vrijednosti

$$
\lambda_n = \frac{n^2\pi^2}{4}, \quad n\in \mathbb{N}\cup \{0\},
$$

i pripadne svojstvene funkcije 

$$ 
X_n(x)= A_n \cos \big(\frac{n\pi}{2}x\big ).
$$

Za svaki $\lambda_n$ rješenje populacijske jednadžbe glasi 

$$
T_n(t)=B_n e^{\displaystyle-\frac{n^2\pi^2}{4} t}
$$

što zajedno daje 

$$
u_n(x,t)= C_n \cos \big(\frac{n\pi}{2}x\big ) e^{\displaystyle-\frac{n^2\pi^2}{4} t}.
$$

Svaka funkcija $u_n$ zadovoljava jednadžbu i rubne uvjete. 

Prema __principu superpozicije__ i funkcija 

$$
u(x,t)=\sum_{n=0}^\infty u_n(x,t)= \sum_{n=0}^\infty C_n \cos \big(\frac{n\pi}{2}x\big ) e^{\displaystyle-\frac{n^2\pi^2}{4} t}
$$

također zadovoljava jednadžbu i rubne uvjete. Treba još odabrati koeficijente $C_n$ tako da se zadovolji i početni uvijet - radi se o razvoju u __(generalizirani) Fourierov red__ :

\begin{align*}
& u(x,0)=\sum_{n=0}^\infty C_n \cos \big(\frac{n\pi}{2}x\big )=|x| \\
& C_n=  \displaystyle \frac{ \big(|x|, \cos \big(\frac{n\pi}{2}x\big ) \big)}
{\big (\cos \big(\frac{n\pi}{2}x\big ), \cos \big(\frac{n\pi}{2}x\big ) \big)} \tag{*}
\end{align*}

Probajmo simboličko računanje - treba nam paket `SymPy.jl`:

In [1]:
using SymPy

In [2]:
# Definirajmo simbole
n=symbols("n",integer=True,nonnegative=True)
x=symbols("x",real=True)

x

In [3]:
using LinearAlgebra

In [4]:
# Definirajmo skalarni produkt
import LinearAlgebra.⋅
⋅(f,g,a,b)=integrate(f*g,(x,a,b))

dot (generic function with 34 methods)

In [5]:
# Umjesto 
g=abs(x)
# g(x)=x*Heaviside(x)-x*Heaviside(-x)

│x│

Za crtanje koristimo paket `Plots.jl` i backend `plotly()`.

In [6]:
using Plots
plotly()

Plots.PlotlyBackend()

In [8]:
plot(g(x),-2,2)

<!DOCTYPE html>
 
 
 Plots.jl

In [9]:
f(n,x)=cos(n*PI*x/2)

f (generic function with 1 method)

In [10]:
# Na primjer
f(2,x)

cos(π⋅x)

In [11]:
f(0,x)

1

Izračunajmo koeficijente $C_n$:

In [12]:
C(n)=⋅(g(x),f(n,x),-2,2)/⋅(f(n,x),f(n,x),-2,2)

C (generic function with 1 method)

In [13]:
C(0)

1

In [14]:
C(1)

-8 
───
  2
 π 

In [15]:
C(2)

0

In [16]:
C(3)

-8  
────
   2
9⋅π 

In [17]:
C(4)

0

In [18]:
C(5)

 -8  
─────
    2
25⋅π 

In [19]:
# Opća formula
⋅(g(x),f(n,x),-2,2)/⋅(f(n,x),f(n,x),-2,2)

                  ⎛⎧      n                   ⎞
                  ⎜⎪8⋅(-1)      8             ⎟
⎛⎧1/2  for n ≠ 0⎞ ⎜⎪─────── - ─────  for n ≠ 0⎟
⎜⎨              ⎟⋅⎜⎨  2  2     2  2           ⎟
⎝⎩1/4  otherwise⎠ ⎜⎪ π ⋅n     π ⋅n            ⎟
                  ⎜⎪                          ⎟
                  ⎝⎩       4         otherwise⎠

Vidimo da je 

\begin{align}
& C_0=1, \\
& C_{2k}=0, \\
& C_{2k-1}=\displaystyle\frac{-8}{(2k-1)^2\pi^2},
\end{align}

odnosno

$$
u(x,t)=1 - \sum_{k=1}^\infty \frac{8}{(2k-1)^2\pi^2}
\cos \bigg(\frac{(2k-1)\pi}{2}x\bigg ) e^{\displaystyle-\frac{(2k-1)^2\pi^2}{4} t}.
$$

Definirajmo sumu prvih $n$ članova reda:

In [20]:
k=symbols("k", integer=True, nonnegative=True)
t=symbols("t", real=True, nonnegative=True)

t

In [21]:
u(n,x,t)=C(n)*f(n,x)*exp(-(n^2*PI^2/4)*t)

u (generic function with 1 method)

In [22]:
# Na primjer
u(0,x,t)

1

In [23]:
u(3,x,t)

        2               
    -9⋅π ⋅t             
    ────────            
       4        ⎛3⋅π⋅x⎞ 
-8⋅ℯ        ⋅cos⎜─────⎟ 
                ⎝  2  ⎠ 
────────────────────────
             2          
          9⋅π           

In [24]:
# u(3,x,t) u zadanoj točki
u(3,0.5,0.5)

            2             
    -1.125⋅π              
-8⋅ℯ         ⋅cos(0.75⋅π) 
──────────────────────────
              2           
           9⋅π            

In [25]:
# Numerička vrijednost
N(u(3,0.5,0.5))

9.592430540562468751472090382161178189698489151335243936752010738066994113725231e-07

In [26]:
# Suma prvih n članova reda
U(n,x,t)=sum([u(k,x,t) for k=0:n])

U (generic function with 1 method)

In [27]:
# Na primjer
U(5,0.5,0.5)

                2                 2              2                
        -0.125⋅π          -3.125⋅π       -1.125⋅π                 
  4⋅√2⋅ℯ            4⋅√2⋅ℯ            8⋅ℯ         ⋅cos(0.75⋅π)    
- ─────────────── + ─────────────── - ──────────────────────── + 1
          2                  2                     2              
         π               25⋅π                   9⋅π               

In [28]:
# Numerička vrijednost
N(U(5,0.5,0.5))

0.8330895966582437477415034267542879745236008661595193870885264512109283990120554

In [29]:
# Za t=0 ovo mora konvergirati u |x|
@time N(U(11,0.5,0.0))

  1.389633 seconds (5.87 k allocations: 153.906 KiB)


0.4994152381404319713930517572608357654281954907461756811703554062543148448070287

__Napomena:__ Radi se o simboličkom računanju pa ne treba pretjerivati s $n$.

### Crtanje

In [30]:
m=17
X=range(-2,2, length=m)
T=range(0,5,length=m)

0.0:0.3125:5.0

In [31]:
X

-2.0:0.25:2.0

In [32]:
collect(X)

17-element Array{Float64,1}:
 -2.0
 -1.75
 -1.5
 -1.25
 -1.0
 -0.75
 -0.5
 -0.25
  0.0
  0.25
  0.5
  0.75
  1.0
  1.25
  1.5
  1.75
  2.0

In [33]:
# Radi brzine pripremimo U(9)
U9=U(9,x,t)

         2                      2                         2                   
       -π ⋅t                -9⋅π ⋅t                  -25⋅π ⋅t                 
       ──────               ────────                 ─────────                
         4       ⎛π⋅x⎞         4        ⎛3⋅π⋅x⎞          4        ⎛5⋅π⋅x⎞     
    8⋅ℯ      ⋅cos⎜───⎟   8⋅ℯ        ⋅cos⎜─────⎟   8⋅ℯ         ⋅cos⎜─────⎟   8⋅
                 ⎝ 2 ⎠                  ⎝  2  ⎠                   ⎝  2  ⎠     
1 - ────────────────── - ────────────────────── - ─────────────────────── - ──
             2                       2                         2              
            π                     9⋅π                      25⋅π               

      2                         2              
 -49⋅π ⋅t                  -81⋅π ⋅t            
 ─────────                 ─────────           
     4        ⎛7⋅π⋅x⎞          4        ⎛9⋅π⋅x⎞
ℯ         ⋅cos⎜─────⎟   8⋅ℯ         ⋅cos⎜─────⎟
              ⎝  2  ⎠                   ⎝  2  ⎠


In [34]:
# Sada je puno brže jer se samo uvrštava.
@time N(U9(0,2.0))

  0.163170 seconds (219.49 k allocations: 11.702 MiB)


0.9941704789261603549294538451352932365437590319983161418834018310530498671650985

In [38]:
# Ovo je sada brzo
# (16*16*0.005=3 sekunde)
z = zeros(m,m)
for i in 1:m
    for j in 1:m
        z[i,j] = Float64(U9(X[i],T[j]))
    end
end

In [39]:
z

17×17 Array{Float64,2}:
 1.9596     1.37499   1.1734    1.0802    …  1.00002   1.00001   1.0
 1.7464     1.3464    1.1602    1.0741       1.00002   1.00001   1.0
 1.50532    1.26504   1.12261   1.05671      1.00001   1.00001   1.0
 1.24678    1.14339   1.06636   1.03069      1.00001   1.0       1.0
 1.0        1.0       1.0       1.0          1.0       1.0       1.0
 0.753221   0.85661   0.933642  0.969308  …  0.999994  0.999997  0.999999
 0.494678   0.734963  0.877386  0.943289     0.999988  0.999995  0.999997
 0.253602   0.653599  0.839798  0.925903     0.999985  0.999993  0.999997
 0.0403952  0.625007  0.826598  0.919798     0.999983  0.999992  0.999996
 0.253602   0.653599  0.839798  0.925903     0.999985  0.999993  0.999997
 0.494678   0.734963  0.877386  0.943289  …  0.999988  0.999995  0.999997
 0.753221   0.85661   0.933642  0.969308     0.999994  0.999997  0.999999
 1.0        1.0       1.0       1.0          1.0       1.0       1.0
 1.24678    1.14339   1.06636   1.03069     

In [41]:
surface(X,T,z',xlabel="x",ylabel="t")

<!DOCTYPE html>
 
 
 Plots.jl

### Numeričko računanje i crtanje

In [42]:
X=range(-2,2,length=51)
T=range(0,5,length=51)
XT=collect(Iterators.product(X,T))

51×51 Array{Tuple{Float64,Float64},2}:
 (-2.0, 0.0)   (-2.0, 0.1)   (-2.0, 0.2)   …  (-2.0, 4.9)   (-2.0, 5.0)
 (-1.92, 0.0)  (-1.92, 0.1)  (-1.92, 0.2)     (-1.92, 4.9)  (-1.92, 5.0)
 (-1.84, 0.0)  (-1.84, 0.1)  (-1.84, 0.2)     (-1.84, 4.9)  (-1.84, 5.0)
 (-1.76, 0.0)  (-1.76, 0.1)  (-1.76, 0.2)     (-1.76, 4.9)  (-1.76, 5.0)
 (-1.68, 0.0)  (-1.68, 0.1)  (-1.68, 0.2)     (-1.68, 4.9)  (-1.68, 5.0)
 (-1.6, 0.0)   (-1.6, 0.1)   (-1.6, 0.2)   …  (-1.6, 4.9)   (-1.6, 5.0)
 (-1.52, 0.0)  (-1.52, 0.1)  (-1.52, 0.2)     (-1.52, 4.9)  (-1.52, 5.0)
 (-1.44, 0.0)  (-1.44, 0.1)  (-1.44, 0.2)     (-1.44, 4.9)  (-1.44, 5.0)
 (-1.36, 0.0)  (-1.36, 0.1)  (-1.36, 0.2)     (-1.36, 4.9)  (-1.36, 5.0)
 (-1.28, 0.0)  (-1.28, 0.1)  (-1.28, 0.2)     (-1.28, 4.9)  (-1.28, 5.0)
 (-1.2, 0.0)   (-1.2, 0.1)   (-1.2, 0.2)   …  (-1.2, 4.9)   (-1.2, 5.0)
 (-1.12, 0.0)  (-1.12, 0.1)  (-1.12, 0.2)     (-1.12, 4.9)  (-1.12, 5.0)
 (-1.04, 0.0)  (-1.04, 0.1)  (-1.04, 0.2)     (-1.04, 4.9)  (-1.04, 5.0)
 ⋮             

In [43]:
# Probajmo l od 1 do 10
l=5
h(xt)=1-8*sum([cos.((2*k-1)*pi*xt[1]/2).*exp.(-(2*k-1)^2*pi^2*xt[2]/4)/((2*k-1)^2*π^2) 
        for k=1:l])
surface(X,T,map(h,XT)',xlabel="x",ylabel="t")

<!DOCTYPE html>
 
 
 Plots.jl

## Primjer 1

\begin{align*}
& u_t-u_{xx}=-u \\
& u(x,0)=f(x)=\begin{cases}0, \quad -1<x<0 \\ x,\quad 0<x<1 \end{cases} \\
& u(-1,t)=0,\quad u(1,t)=0 
\end{align*}

Za detalje o simboličkom računanju pogledajte
[SymPy Tutorial](https://github.com/jverzani/SymPy.jl/blob/master/examples/tutorial.md).

Uvrštavanjem

$$
u(x,t)=X(x)T(t)
$$

jednadžba prelazi u jednadžbu

$$
T'X-TX''=-TX,
$$

što daje dvije jednadžbe:

$$
\frac{X''}{X}=\frac{T'+T}{T}=-\lambda.
$$

Jednadžba po $T$ je populacijska jednadžba koja glasi

$$
T'=-(\lambda+1)T
$$

i čije rješenje je

$$
T=Ce^{-(\lambda+1)t}.
$$

Riješimo SLP po $X$:

$$
X''=-\lambda X, \quad X(-1)=0, \quad X(1)=0.
$$

In [44]:
F = SymFunction("F")

F

In [45]:
l=symbols("l",real=true,positive=true)
diffeq = Eq(diff(F(x), x, x) +l*F(x), 0)

           2          
          d           
l⋅F(x) + ───(F(x)) = 0
           2          
         dx           

In [46]:
ex = dsolve(diffeq)

F(x) = C₁⋅sin(√l⋅x) + C₂⋅cos(√l⋅x)

In [47]:
ex1 = rhs(ex)

C₁⋅sin(√l⋅x) + C₂⋅cos(√l⋅x)

Uvrstimo rubne uvjete:

In [48]:
ex1a=subs(ex1,x,-1)

-C₁⋅sin(√l) + C₂⋅cos(√l)

In [49]:
ex1b=subs(ex1,x,1)

C₁⋅sin(√l) + C₂⋅cos(√l)

In [50]:
solve(cos(sqrt(l)),l)

2-element Array{Sym,1}:
   pi^2/4
 9*pi^2/4

Sustav jednadžbi je homogen i glasi

$$
\begin{bmatrix} -C_1 & C_2 \\ C_1 & C_2 \end{bmatrix} \begin{bmatrix}\sin \sqrt{\lambda} \\ \cos\sqrt{\lambda} \end{bmatrix} = \begin{bmatrix} 0\\ 0\end{bmatrix}.
$$

Trivijalno rješenje je u ovom slučaju očito nemoguće, a netrivijalna rješenje postoje kada je 
matrica sustava singularna, odnosno kada je $C_1=0$ ili $C_2=0$.

Kada je $C_1=0$ onda je $\cos\sqrt{\lambda}=0$ pa je 

$$
\sqrt{\lambda}=\frac{2n+1}{2}\pi, \quad n=0,1,2,3,\ldots
$$

Kada je $C_2=0$ onda je $\sin\sqrt{\lambda}=0$ pa je 

$$
\sqrt{\lambda}=n\pi, \quad n=0,1,2,3,\ldots
$$

Dakle, rješenje problema koje zadovoljava jednadžbu i rubne uvjete ima oblik:

\begin{equation*}
u(x,t)=\sum_{n=0}^\infty a_n \cos \bigg(\frac{2n+1}{2}\pi x\bigg)
e^{-\big(\big[\frac{2n+1}{2}\pi\big]^2+1\big)t}+b_n \sin (n\pi x)\,e^{-([n\pi]^2+1)t}.
\end{equation*}

Potrebno je zadovoljiti još početni uvjet:

\begin{equation*}
u(x,0)=\sum_{n=0}^\infty a_n \cos \bigg(\frac{2n+1}{2}\pi x\bigg)+b_n \sin (n\pi x)=f(x).
\end{equation*}
 
Radi se o razvoju u generalizirani Fourierov red funkcije f(x): 

In [51]:
# p=piecewise((0,Lt(x,0)),(x,Ge(x,0)))
p(x)=x*Heaviside(x)

p (generic function with 1 method)

Provjerimo ortonormiranost sustava funkcija.

In [52]:
⋅(cos((2*n+1)*PI*x/2),cos((2*n+1)*PI*x/2),-1,1)

1

In [53]:
⋅(sin(n*PI*x),sin(n*PI*x),-1,1)

⎧1  for n ≠ 0
⎨            
⎩0  otherwise

Norme svih funkcija su jednake $1$ pa ne trebamo računati nazivnike.

In [54]:
a(n)=⋅(p(x),cos((2*n+1)*PI*x/2),-1,1)

a (generic function with 1 method)

In [55]:
a(0)

  4    2
- ── + ─
   2   π
  π     

In [56]:
N(a(0))

0.2313350377982302573000172006511468925204034842728395996082332486588947066879649

In [57]:
b(n)=⋅(p(x),sin(n*PI*x),-1,1)

b (generic function with 1 method)

In [58]:
b(0)

0

In [59]:
b(17)

 1  
────
17⋅π

In [60]:
# Opća formule za a(n)
⋅(p(x),cos((2*n+1)*PI*x/2),-1,1)

       n                
 2⋅(-1)          4      
───────── - ────────────
2⋅π⋅n + π              2
            (2⋅π⋅n + π) 

In [61]:
# Opća formule za b(n)
⋅(p(x),sin(n*PI*x),-1,1)

⎧   0     for n = 0
⎪                  
⎪     n            
⎨-(-1)             
⎪───────  otherwise
⎪  π⋅n             
⎩                  

Pripremimo se za brže računanje tako da ćemo unaprijed izračunati numeričke
vrijednosti koeficijenata $a_n$ i $b_n$. 

In [62]:
A=[Float64(a(n)) for n=0:20]

21-element Array{Float64,1}:
  0.23133503779823025
 -0.2572382279635661
  0.11111256509074223
 -0.0992167987988249
  0.06573201502146767
 -0.06122398537696484
  0.04657261719650418
 -0.04424258364481365
  0.03604585258020599
 -0.03462897620374902
  0.029396214252040493
 -0.02844525425146261
  0.024816335319392292
 -0.024134456225643412
  0.02147049781699228
 -0.020957853983313603
  0.018919345962865777
 -0.01851998103464057
  0.01690989542953335
 -0.016590043298425394
  0.015286214118085357

In [63]:
B=[Float64(b(n)) for n=0:20]

21-element Array{Float64,1}:
  0.0
  0.3183098861837907
 -0.15915494309189535
  0.1061032953945969
 -0.07957747154594767
  0.06366197723675814
 -0.05305164769729845
  0.04547284088339867
 -0.039788735772973836
  0.035367765131532294
 -0.03183098861837907
  0.028937262380344605
 -0.026525823848649224
  0.02448537586029159
 -0.022736420441699334
  0.021220659078919377
 -0.019894367886486918
  0.018724110951987685
 -0.017683882565766147
  0.016753151904410034
 -0.015915494309189534

In [64]:
X=range(-1,1,length=51)
T=range(0,5,length=51)
XT=collect(Iterators.product(X,T));

In [65]:
l=20
h(xt)=sum([A[k]*cos.((2*k-1)*pi*xt[1]/2).*exp.(-(((2*k-1)*pi/2)^2/4+1)*xt[2])+
        B[k]*sin.((k-1)*pi*xt[1]).*exp.(-(((k-1)*pi)^2+1)*xt[2]) for k=1:l]) 
surface(X,T,map(h,XT)',xlabel="x",ylabel="t")

<!DOCTYPE html>
 
 
 Plots.jl

## Homogenizacija

U oba prethodna primjera zadani su homogeni rubni uvjeti. Ukoliko rubni uvjeti nisu homogeni, 
zadani problem je potrebno __homogenizirati__ kako bi mogli dobiti regularni SLP.

Navedimo primjer. Neka je zadan problem

\begin{align*}
& u_t -u_{xx}=0,\quad 0<x<l,\quad t>0 \\
& u(x,0)=f(x),\quad 0<x<l \\
& u(0,t)=g(t),\quad u(l,t)=h(t),\quad t>0.
\end{align*}
 
Nađimo rješenje u obliku

$$
u(x,t)=v(x,t)+U(x,t),
$$

gdje je $v$ rješenje problema sa homogenim rubnim uvjetima. Vrijedi

\begin{align*}
& u=v+U\\
& u_t=v_t+U_t\\
& u_{xx}=v_{xx}+U_{xx}
\end{align*}

pa zadana PDJ prelazi u 

$$
v_t+U_t=v_{xx}+U_{xx}.
$$

Početni uvjet za $v$ glasi

$$
v(x,0)=u(x,0)-U(x,0)=f(x)-U(x,0),
$$

a rubni uvjeti glase

\begin{align*}
& v(0,t)=u(0,t)-U(0,t)=g(t)-U(0,t)=0\quad  \textrm{(želimo homogeni uvjet)}\\
& v(l,t)=u(l,t)-U(l,t)=h(t)-U(l,t)=0 \quad  \textrm{(želimo homogeni uvjet)}
\end{align*}

Zaključujemo da će $v$ zadovoljavati homogene rubne uvjete ako je 

$$
U(x,t)=g(t)+\displaystyle\frac{x}{l}[h(t)-g(t)],\quad 0<x<l.
$$

Za ovako definiranu funkciju $U$ vrijedi

\begin{align*}
& U_t=g'(t)+\displaystyle\frac{x}{l}[h'(t)-g'(t)]\\
& U_{xx}=0.
\end{align*}

Uvrštavanjem slijedi da je $v$ rješenje __homogenog__ reakcijsko-difuzijskog problema

\begin{align*}
&v_t=v_{xx}-g'(t)-\displaystyle\frac{x}{l}[h'(t)-g'(t)], \quad 0<x<l,\quad t>0
\\
&v(x,0)=f(x)-g(0)-\displaystyle\frac{x}{l}[h(0)-g(0)], \quad 0<x<l
\\
& v(0,t)=0,\quad v(l,t)=0,\quad t>0,
\end{align*}

dok je rješenje polaznog problema

$$
u(x,t)=v(x,t)+g(t)+\displaystyle\frac{x}{l}[h(t)-g(t)].
$$